routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Pages
Route::get('/', 'PagesController@home')->name('home');

// Auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('postLogin');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register')->name('postRegister');

// Dashboard
Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');

// VisitReasons
Route::resource('visitreasons', 'VisitReasonsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Designations
Route::resource('designations', 'DesignationsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Hosts
Route::resource('hosts', 'HostsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Visitors
Route::resource('visitors', 'VisitorsController', ['only' => ['index', 'destroy']]);

// Visits
Route::get('visits/approved', 'VisitsController@approved')->name('visits.approved');
Route::get('visits/pending', 'VisitsController@pending')->name('visits.pending');
Route::get('visits/rejected', 'VisitsController@rejected')->name('visits.rejected');
Route::resource('visits', 'VisitsController');

// Profiles
Route::resource('profiles', 'ProfilesController');

// Appointments
Route::get('appointments/specific/{id}', 'AppointmentsController@specific')->name('appointments.specific');
Route::get('appointments/approved', 'AppointmentsController@approved')->name('appointments.approved');
Route::get('appointments/pending', 'AppointmentsController@pending')->name('appointments.pending');
Route::get('appointments/rejected', 'AppointmentsController@rejected')->name('appointments.rejected');
Route::resource('appointments', 'AppointmentsController');

// Manage Visits
Route::get('managevisits/approved', 'ManageVisitsController@approved')->name('managevisits.approved');
Route::get('managevisits/pending', 'ManageVisitsController@pending')->name('managevisits.pending');
Route::get('managevisits/rejected', 'ManageVisitsController@rejected')->name('managevisits.rejected');
Route::resource('managevisits', 'ManageVisitsController');

// Visit Access Codes
Route::get('visits/approved/download/{id}', 'VisitAccessCodesController@download')->name('visitDownload');

// Manage Appointments
Route::get('manageappointments/approved', 'ManageAppointmentsController@approved')->name('manageappointments.approved');
Route::get('manageappointments/pending', 'ManageAppointmentsController@pending')->name('manageappointments.pending');
Route::get('manageappointments/rejected', 'ManageAppointmentsController@rejected')->name('manageappointments.rejected');
Route::resource('manageappointments', 'ManageAppointmentsController');

// Appointment Access Codes
Route::get('appointments/approved/download/{id}', 'AppointmentAccessCodesController@download')->name('appointmentDownload');

// Mail
Route::post('mail/{id}', 'MailController@send')->name('mail.send');

// Visit Reports
Route::get('checkvisits', 'VisitReportsController@index')->name('checkVisits.index');
Route::post('checkvisits', 'VisitReportsController@check')->name('checkVisits.check');
Route::post('checkvisits/proceed', 'VisitReportsController@proceed')->name('checkVisits.proceed');
Route::post('checkvisits/terminate', 'VisitReportsController@terminate')->name('checkVisits.terminate');

// Appointment Reports
Route::get('checkappointments', 'AppointmentReportsController@index')->name('checkAppointments.index');
Route::post('checkappointments', 'AppointmentReportsController@check')->name('checkAppointments.check');
Route::post('checkappointments/proceed', 'AppointmentReportsController@proceed')->name('checkAppointments.proceed');
Route::post('checkappointments/terminate', 'AppointmentReportsController@terminate')->name('checkAppointments.terminate');

// AR Visit Reports
Route::get('visitreports', 'ARVisitReportsController@index')->name('visitReports.index');
Route::get('visitreports/{id}', 'ARVisitReportsController@show')->name('visitReports.show');
Route::get('visitstoday', 'ARVisitReportsController@today')->name('visitReports.today');

// AR Appointment Reports
Route::get('appointmentreports', 'ARAppointmentReportsController@index')->name('appointmentReports.index');
Route::get('appointmentreports/{id}', 'ARAppointmentReportsController@show')->name('appointmentReports.show');
Route::get('appointmentstoday', 'ARAppointmentReportsController@today')->name('appointmentReports.today');

// Inbox
Route::get('inbox', 'InboxesController@index')->name('inbox.index');
Route::post('inbox/{id}', 'InboxesController@store')->name('inbox.store');

// Immediate Visits
Route::resource('immediatevisits', 'ImmediateVisitsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Immediate Appointments
Route::resource('immediateappointments', 'ImmediateAppointmentsController', ['only' => ['index', 'create', 'store', 'show', 'destroy']]);

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Visit;
use App\Appointment;
use App\VisitReport;
use App\AppointmentReport;
use Auth;

class DashboardController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}

    public function dashboard()
    {
    	$visitors=User::where('role', 'visitor')->get()->count();
    	$hosts=User::where('role', 'host')->get()->count();

    	if(Auth::user()->role=='admin' || Auth::user()->role=='receptionist'){
	    	$visitRequests=Visit::all()->count();
	    	$approvedVisitRequests=Visit::where('status', 1)->get()->count();
	    	$pendingVisitRequests=Visit::where('status', 0)->get()->count();
	    	$rejectedVisitRequests=Visit::where('status', -1)->get()->count();
	    	$visitedToday=VisitReport::whereDate('entryTimestamp', date('Y-m-d'))->where('status', '1')->get()->count();

	    	$appointmentRequests=Appointment::all()->count();
	    	$approvedAppointmentRequests=Appointment::where('status', 1)->get()->count();
	    	$pendingAppointmentRequests=Appointment::where('status', 0)->get()->count();
	    	$rejectedAppointmentRequests=Appointment::where('status', -1)->get()->count();
	    	$appointmentToday=AppointmentReport::whereDate('entryTimestamp', date('Y-m-d'))->where('status', '1')->get()->count();
	    }

	    else if(Auth::user()->role=='visitor'){
	    	$visitRequests=Visit::where('visitorId', Auth::user()->id)->count();
	    	$approvedVisitRequests=Visit::where([['visitorId', '=', Auth::user()->id], ['status', '=', 1]])->get()->count();
	    	$pendingVisitRequests=Visit::where([['visitorId', '=', Auth::user()->id], ['status', '=', 0]])->get()->count();
	    	$rejectedVisitRequests=Visit::where([['visitorId', '=', Auth::user()->id], ['status', '=', -1]])->get()->count();
	    	$visitedToday=0;

	    	$appointmentRequests=Appointment::where('visitorId', Auth::user()->id)->count();
	    	$approvedAppointmentRequests=Appointment::where([['visitorId', '=', Auth::user()->id], ['status', '=', 1]])->get()->count();
	    	$pendingAppointmentRequests=Appointment::where([['visitorId', '=', Auth::user()->id], ['status', '=', 0]])->get()->count();
	    	$rejectedAppointmentRequests=Appointment::where([['visitorId', '=', Auth::user()->id], ['status', '=', -1]])->get()->count();
	    	$appointmentToday=0;
	    }

	    else if(Auth::user()->role=='host'){
	    	$visitRequests=0;
	    	$approvedVisitRequests=0;
	    	$pendingVisitRequests=0;
	    	$rejectedVisitRequests=0;
	    	$visitedToday=0;

	    	$appointmentRequests=Appointment::where('hostId', Auth::user()->id)->count();
	    	$approvedAppointmentRequests=Appointment::where([['hostId', '=', Auth::user()->id], ['status', '=', 1]])->get()->count();
	    	$pendingAppointmentRequests=Appointment::where([['hostId', '=', Auth::user()->id], ['status', '=', 0]])->get()->count();
	    	$rejectedAppointmentRequests=Appointment::where([['hostId', '=', Auth::user()->id], ['status', '=', -1]])->get()->count();
	    	$appointmentToday=0;
	    }

    	$data=[
    		'visitors' => $visitors,
    		'hosts' => $hosts,
    		'visitRequests' => $visitRequests,
    		'approvedVisitRequests' => $approvedVisitRequests,
    		'pendingVisitRequests' => $pendingVisitRequests,
    		'rejectedVisitRequests' => $rejectedVisitRequests,
    		'visitedToday' => $visitedToday,
    		'appointmentRequests' => $appointmentRequests,
    		'approvedAppointmentRequests' => $approvedAppointmentRequests,
    		'pendingAppointmentRequests' => $pendingAppointmentRequests,
    		'rejectedAppointmentRequests' => $rejectedAppointmentRequests,
    		'appointmentToday' => $appointmentToday
    	];

    	return view('dashboard.index')->withData($data);
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.ap')

@section('title', 'Dashboard')

@section('body')

<div id="content">
	<div id="content-header">
		<div id="breadcrumb"> <a href="{{ route('dashboard') }}" title="Dashboard" class="tip-bottom current"><i class="fa fa-home" aria-hidden="true"></i> Home</a></div>
		{{-- <h1>Add Designation</h1> --}}
	</div>
	
	<div class="container-fluid">
		{{-- <hr> --}}
		<br><br>
		<div class="row-fluid">
			<div class="span12">
				@if(Auth::user()->role=='admin')
				<div class="quick-actions_homepage">
					<ul class="quick-actions">
						<li class="bg_lb span3"><a href="{{ route('visitors.index') }}"><i class="fa fa-user fa-2x"></i><br><span class="label label-inverse">{{ $data['visitors'] }}</span>Visitors</a></li>
						<li class="bg_lg span3"><a href="{{ route('hosts.index') }}"><i class="fa fa-user fa-2x"></i><br><span class="label label-inverse">{{ $data['hosts'] }}</span>Hosts</a></li>
					</ul>
				</div>
				<div class="quick-actions_homepage">
					<ul class="quick-actions">
						<li class="bg_ly span2"><a href="{{ route('managevisits.index') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['visitRequests'] }}</span>Visit Requests</a></li>
						<li class="bg_lg span2"><a href="{{ route('managevisits.approved') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['approvedVisitRequests'] }}</span>Approved</a></li>
						<li class="bg_ls span2"><a href="{{ route('managevisits.pending') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['pendingVisitRequests'] }}</span>Pending</a></li>
						<li class="bg_lo span2"><a href="{{ route('managevisits.rejected') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['rejectedVisitRequests'] }}</span>Rejected</a></li>
					</ul>
				</div>
				@endif

				@if(Auth::user()->role=='visitor')
				<div class="quick-actions_homepage">
					<ul class="quick-actions">
						<li class="bg_ly span2"><a href="{{ route('visits.index') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['visitRequests'] }}</span>Visit Requests</a></li>
						<li class="bg_lg span2"><a href="{{ route('visits.approved') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['approvedVisitRequests'] }}</span>Approved</a></li>
						<li class="bg_ls span2"><a href="{{ route('visits.pending') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['pendingVisitRequests'] }}</span>Pending</a></li>
						<li class="bg_lo span2"><a href="{{ route('visits.rejected') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['rejectedVisitRequests'] }}</span>Rejected</a></li>
					</ul>
				</div>
				<div class="quick-actions_homepage">
					<ul class="quick-actions">
						<li class="bg_lo span3"><a href="{{ route('appointments.index') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['appointmentRequests'] }}</span>Appointment Requests</a></li>
						<li class="bg_lg span2"><a href="{{ route('appointments.approved') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['approvedAppointmentRequests'] }}</span>Approved</a></li>
						<li class="bg_ly span2"><a href="{{ route('appointments.pending') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['pendingAppointmentRequests'] }}</span>Pending</a></li>
						<li class="bg_ls span2"><a href="{{ route('appointments.rejected') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['rejectedAppointmentRequests'] }}</span>Rejected</a></li>
					</ul>
				</div>
				@endif
				
				@if(Auth::user()->role=='host')
				<div class="quick-actions_homepage">
					<ul class="quick-actions">
						<li class="bg_lo span3"><a href="{{ route('manageappointments.index') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['appointmentRequests'] }}</span>Appointment Requests</a></li>
						<li class="bg_lg span2"><a href="{{ route('manageappointments.approved') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['approvedAppointmentRequests'] }}</span>Approved</a></li>
						<li class="bg_ly span2"><a href="{{ route('manageappointments.pending') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['pendingAppointmentRequests'] }}</span>Pending</a></li>
						<li class="bg_ls span2"><a href="{{ route('manageappointments.rejected') }}"><i class="fa fa-server fa-2x"></i><br><span class="label label-inverse">{{ $data['rejectedAppointmentRequests'] }}</span>Rejected</a></li>
					</ul>
				</div>
				@endif

				@if(Auth::user()->role=='admin' || Auth::user()->role=='receptionist')
				<div class="quick-actions_homepage">
					<br>
					<ul class="quick-actions">
						<li class="bg_lr span2"><a href="{{ route('visitReports.today') }}"><i class="fa fa-superpowers fa-2x"></i><br><span class="label label-inverse">{{ $data['visitedToday'] }}</span>Visited Today</a></li>
						<li class="bg_lg span3"><a href="{{ route('appointmentReports.today') }}"><i class="fa fa-superpowers fa-2x"></i><br><span class="label label-inverse">{{ $data['appointmentToday'] }}</span>Appointment Today</a></li>
					</ul>
				</div>
				@endif

			</div>
		</div>
	</div>
</div>

@endsection