routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Pages
Route::get('/', 'PagesController@home')->name('home');

// Auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('postLogin');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register')->name('postRegister');

// Dashboard
Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');

// VisitReasons
Route::resource('visitreasons', 'VisitReasonsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Designations
Route::resource('designations', 'DesignationsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Hosts
Route::resource('hosts', 'HostsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Visitors
Route::resource('visitors', 'VisitorsController', ['only' => ['index', 'destroy']]);

// Visits
Route::get('visits/approved', 'VisitsController@approved')->name('visits.approved');
Route::get('visits/pending', 'VisitsController@pending')->name('visits.pending');
Route::get('visits/rejected', 'VisitsController@rejected')->name('visits.rejected');
Route::resource('visits', 'VisitsController');

// Profiles
Route::resource('profiles', 'ProfilesController');

// Appointments
Route::get('appointments/specific/{id}', 'AppointmentsController@specific')->name('appointments.specific');
Route::get('appointments/approved', 'AppointmentsController@approved')->name('appointments.approved');
Route::get('appointments/pending', 'AppointmentsController@pending')->name('appointments.pending');
Route::get('appointments/rejected', 'AppointmentsController@rejected')->name('appointments.rejected');
Route::resource('appointments', 'AppointmentsController');

// Manage Visits
Route::get('managevisits/approved', 'ManageVisitsController@approved')->name('managevisits.approved');
Route::get('managevisits/pending', 'ManageVisitsController@pending')->name('managevisits.pending');
Route::get('managevisits/rejected', 'ManageVisitsController@rejected')->name('managevisits.rejected');
Route::resource('managevisits', 'ManageVisitsController');

// Visit Access Codes
Route::get('visits/approved/download/{id}', 'VisitAccessCodesController@download')->name('visitDownload');

// Manage Appointments
Route::get('manageappointments/approved', 'ManageAppointmentsController@approved')->name('manageappointments.approved');
Route::get('manageappointments/pending', 'ManageAppointmentsController@pending')->name('manageappointments.pending');
Route::get('manageappointments/rejected', 'ManageAppointmentsController@rejected')->name('manageappointments.rejected');
Route::resource('manageappointments', 'ManageAppointmentsController');

// Appointment Access Codes
Route::get('appointments/approved/download/{id}', 'AppointmentAccessCodesController@download')->name('appointmentDownload');

// Mail
Route::post('mail/{id}', 'MailController@send')->name('mail.send');

// Visit Reports
Route::get('checkvisits', 'VisitReportsController@index')->name('checkVisits.index');
Route::post('checkvisits', 'VisitReportsController@check')->name('checkVisits.check');
Route::post('checkvisits/proceed', 'VisitReportsController@proceed')->name('checkVisits.proceed');
Route::post('checkvisits/terminate', 'VisitReportsController@terminate')->name('checkVisits.terminate');

// Appointment Reports
Route::get('checkappointments', 'AppointmentReportsController@index')->name('checkAppointments.index');
Route::post('checkappointments', 'AppointmentReportsController@check')->name('checkAppointments.check');
Route::post('checkappointments/proceed', 'AppointmentReportsController@proceed')->name('checkAppointments.proceed');
Route::post('checkappointments/terminate', 'AppointmentReportsController@terminate')->name('checkAppointments.terminate');

// AR Visit Reports
Route::get('visitreports', 'ARVisitReportsController@index')->name('visitReports.index');
Route::get('visitreports/{id}', 'ARVisitReportsController@show')->name('visitReports.show');
Route::get('visitstoday', 'ARVisitReportsController@today')->name('visitReports.today');

// AR Appointment Reports
Route::get('appointmentreports', 'ARAppointmentReportsController@index')->name('appointmentReports.index');
Route::get('appointmentreports/{id}', 'ARAppointmentReportsController@show')->name('appointmentReports.show');
Route::get('appointmentstoday', 'ARAppointmentReportsController@today')->name('appointmentReports.today');

// Inbox
Route::get('inbox', 'InboxesController@index')->name('inbox.index');
Route::post('inbox/{id}', 'InboxesController@store')->name('inbox.store');

// Immediate Visits
Route::resource('immediatevisits', 'ImmediateVisitsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Immediate Appointments
Route::resource('immediateappointments', 'ImmediateAppointmentsController', ['only' => ['index', 'create', 'store', 'show', 'destroy']]);

app/Reason.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reason extends Model
{
    //
}

resources/views/reasons/create.blade.php
@extends('layouts.ap')

@section('title', 'Add Visit Reason')

@section('body')

<div id="content">
	<div id="content-header">
		<div id="breadcrumb"> <a href="{{ route('dashboard') }}" title="Dashboard" class="tip-bottom"><i class="fa fa-home" aria-hidden="true"></i> Home</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('visitreasons.index') }}" class="tip-bottom">Visit Reasons</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('visitreasons.create') }}" class="current">Create</a></div>
		{{-- <h1>Add Visit Reason</h1> --}}
	</div>
	
	<div class="container-fluid">
		<br><br>
		{{-- <hr> --}}
		<div class="row-fluid">
			<div class="span6 offset3">
				<div class="widget-box">
					<div class="widget-title"> <span class="icon"> <i class="fa fa-align-justify" aria-hidden="true"></i> </span>
						<h5>Add Visit Reason</h5>
					</div>
					<div class="widget-content nopadding">
						<form action="{{ route('visitreasons.store') }}" method="POST" class="form-horizontal">
							@if(Session::has('reasonAddSuccess'))
							<div class="alert alert-success">
								<button type="button" class="close" data-dismiss="alert">&times;</button>
								{{ Session::get('reasonAddSuccess') }}
							</div>
							@endif

							{{ csrf_field() }}
							<div class="control-group">
								<label class="control-label">Name of Reason :</label>
								<div class="controls">
									<input type="text" class="span11" name="name" placeholder="Reason name" required>
									@if($errors->has('name'))
									<li class="error">{{ $errors->first('name') }}</li>
									@endif
									<span class="help-block">Reason name should be unique</span>
								</div>
							</div>
							<div class="form-actions">
								<button type="submit" class="btn btn-success">Save</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/reasons/index.blade.php
@extends('layouts.ap')

@section('title', 'Visit Reasons')

@section('body')

<div id="content">
	<div id="content-header">
		<div id="breadcrumb"> <a href="{{ route('dashboard') }}" title="Dashboard" class="tip-bottom"><i class="fa fa-home" aria-hidden="true"></i> Home</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('visitreasons.index') }}" class="current">Visit Reasons</a></div>
		{{-- <h1>Visit Reasons</h1> --}}
	</div>
	
	<div class="container-fluid">
		{{-- <hr> --}}
		<br><br>
		<div class="row-fluid">
			<div class="span10 offset1">
				@if(Session::has('visitReasonUpdated'))
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					{{ Session::get('visitReasonUpdated') }}
				</div>
				@endif
				@if(Session::has('reasonDeleted'))
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					{{ Session::get('reasonDeleted') }}
				</div>
				@endif
				@if(Session::has('reasonDeleteFailed'))
				<div class="alert alert-danger">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					{{ Session::get('reasonDeleteFailed') }}
				</div>
				@endif

				<div class="widget-box">
					<div class="widget-title"> <span class="icon"><i class="fa fa-th"></i></span>
						<h5>Reasons List</h5>
					</div>

					<div class="widget-content nopadding">
						@if($reasons->isEmpty())
							<div class="alert alert-warning">No reason found! <a href="{{ route('visitreasons.create') }}">Add new</a></div>
						@else
						<table class="table table-bordered data-table">
							<thead>
								<tr>
									<th>Sl</th>
									<th>Name</th>
									<th>Created At</th>
									<th>Updated At</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@php($count=0)
								@foreach($reasons as $reason)
								@php($count++)
								<tr>
									<td>{{ $count }}</td>
									<td>{{ ucwords($reason->name) }}</td>
									<td>{{ date('F j, Y, g:i a', strtotime($reason->created_at)) }}</td>
									<td>{{ date('F j, Y, g:i a', strtotime($reason->updated_at)) }}</td>
									<td>
										<button class="btn btn-info btn-mini" data-toggle="modal" data-target="#editReasonModal{{ $reason->id }}"><i class="fa fa-pencil" aria-hidden="true"></i></button>

										<div id="editReasonModal{{ $reason->id }}" class="modal hide">
											<form action="{{ route('visitreasons.update', $reason->id) }}" method="POST">
											{{ csrf_field() }}
											{{ method_field('PUT') }}
											<div class="modal-header">
												<button data-dismiss="modal" class="close" type="button">×</button>
												<h3>Edit</h3>
											</div>
											<div class="modal-body">
												<div class="control-group">
													<label class="control-label">Name of Reason :</label>
													<div class="controls">
														<input type="text" class="span12" name="name" placeholder="Reason name" value="{{ $reason->name }}" required>
														@if($errors->has('name'))
														<li class="error">{{ $errors->first('name') }}</li>
														@endif
														<span class="help-block">Reason name should be unique</span>
													</div>
												</div>
											</div>
											<div class="modal-footer">
												<button type="submit" class="btn btn-primary">Save</button>
												<button data-dismiss="modal" class="btn">Cancel</button>
											</div>
											</form>
										</div>

										<form action="{{ route('visitreasons.destroy', $reason->id) }}" method="POST" class="form-inline">
											{{ csrf_field() }}
											{{ method_field('DELETE') }}
											<button type="submit" class="btn btn-danger btn-mini" onclick="return confirm('Are you sure?')"><i class="fa fa-trash" aria-hidden="true"></i></button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						@endif
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

@endsection