routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Pages
Route::get('/', 'PagesController@home')->name('home');

// Auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('postLogin');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register')->name('postRegister');

// Dashboard
Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');

// VisitReasons
Route::resource('visitreasons', 'VisitReasonsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Designations
Route::resource('designations', 'DesignationsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Hosts
Route::resource('hosts', 'HostsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Visitors
Route::resource('visitors', 'VisitorsController', ['only' => ['index', 'destroy']]);

// Visits
Route::get('visits/approved', 'VisitsController@approved')->name('visits.approved');
Route::get('visits/pending', 'VisitsController@pending')->name('visits.pending');
Route::get('visits/rejected', 'VisitsController@rejected')->name('visits.rejected');
Route::resource('visits', 'VisitsController');

// Profiles
Route::resource('profiles', 'ProfilesController');

// Appointments
Route::get('appointments/specific/{id}', 'AppointmentsController@specific')->name('appointments.specific');
Route::get('appointments/approved', 'AppointmentsController@approved')->name('appointments.approved');
Route::get('appointments/pending', 'AppointmentsController@pending')->name('appointments.pending');
Route::get('appointments/rejected', 'AppointmentsController@rejected')->name('appointments.rejected');
Route::resource('appointments', 'AppointmentsController');

// Manage Visits
Route::get('managevisits/approved', 'ManageVisitsController@approved')->name('managevisits.approved');
Route::get('managevisits/pending', 'ManageVisitsController@pending')->name('managevisits.pending');
Route::get('managevisits/rejected', 'ManageVisitsController@rejected')->name('managevisits.rejected');
Route::resource('managevisits', 'ManageVisitsController');

// Visit Access Codes
Route::get('visits/approved/download/{id}', 'VisitAccessCodesController@download')->name('visitDownload');

// Manage Appointments
Route::get('manageappointments/approved', 'ManageAppointmentsController@approved')->name('manageappointments.approved');
Route::get('manageappointments/pending', 'ManageAppointmentsController@pending')->name('manageappointments.pending');
Route::get('manageappointments/rejected', 'ManageAppointmentsController@rejected')->name('manageappointments.rejected');
Route::resource('manageappointments', 'ManageAppointmentsController');

// Appointment Access Codes
Route::get('appointments/approved/download/{id}', 'AppointmentAccessCodesController@download')->name('appointmentDownload');

// Mail
Route::post('mail/{id}', 'MailController@send')->name('mail.send');

// Visit Reports
Route::get('checkvisits', 'VisitReportsController@index')->name('checkVisits.index');
Route::post('checkvisits', 'VisitReportsController@check')->name('checkVisits.check');
Route::post('checkvisits/proceed', 'VisitReportsController@proceed')->name('checkVisits.proceed');
Route::post('checkvisits/terminate', 'VisitReportsController@terminate')->name('checkVisits.terminate');

// Appointment Reports
Route::get('checkappointments', 'AppointmentReportsController@index')->name('checkAppointments.index');
Route::post('checkappointments', 'AppointmentReportsController@check')->name('checkAppointments.check');
Route::post('checkappointments/proceed', 'AppointmentReportsController@proceed')->name('checkAppointments.proceed');
Route::post('checkappointments/terminate', 'AppointmentReportsController@terminate')->name('checkAppointments.terminate');

// AR Visit Reports
Route::get('visitreports', 'ARVisitReportsController@index')->name('visitReports.index');
Route::get('visitreports/{id}', 'ARVisitReportsController@show')->name('visitReports.show');
Route::get('visitstoday', 'ARVisitReportsController@today')->name('visitReports.today');

// AR Appointment Reports
Route::get('appointmentreports', 'ARAppointmentReportsController@index')->name('appointmentReports.index');
Route::get('appointmentreports/{id}', 'ARAppointmentReportsController@show')->name('appointmentReports.show');
Route::get('appointmentstoday', 'ARAppointmentReportsController@today')->name('appointmentReports.today');

// Inbox
Route::get('inbox', 'InboxesController@index')->name('inbox.index');
Route::post('inbox/{id}', 'InboxesController@store')->name('inbox.store');

// Immediate Visits
Route::resource('immediatevisits', 'ImmediateVisitsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Immediate Appointments
Route::resource('immediateappointments', 'ImmediateAppointmentsController', ['only' => ['index', 'create', 'store', 'show', 'destroy']]);

app/Http/Controllers/HostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Designation;
use App\User;
use App\HostsDesignation;
use Session;
use DB;
use App\Profile;
use App\Appointment;

class HostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('App\Http\Middleware\AdminMiddleware');
    }
    
    public function index()
    {
        $hosts=DB::table('users')->join('hosts_designations', 'users.id', '=', 'hosts_designations.hostId')
                                ->join('designations', 'hosts_designations.designationId', '=', 'designations.id')
                                ->where('users.role', 'host')
                                ->select('users.*', 'designations.name as designation')
                                ->orderBy('users.id', 'DESC')
                                ->get();
        return view('hosts.index')->withHosts($hosts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $designations=Designation::orderBy('name', 'ASC')->get();
        return view('hosts.create')->withDesignations($designations);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|string|min:5|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'designationId' => 'required',
            'role' => 'required',
            'password' => 'required|string|min:5|confirmed',
        ));

        $user=new User();
        $user->name=ucwords($request->name);
        $user->email=strtolower($request->email);
        $user->role=strtolower($request->role);
        $user->password=bcrypt($request->password);
        $user->save();

        $hostDesignation=new HostsDesignation();
        $hostDesignation->hostId=$user->id;
        $hostDesignation->designationId=$request->designationId;
        $hostDesignation->save();

        Session::flash('hostAddSuccess', 'Successfully host added!');
        return redirect()->route('hosts.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $profile=Profile::where('userId', $id)->first();
        $appointments=Appointment::where('hostId', $id)->first();

        if(empty($profile) && empty($appointments)){
            $hostDesignation=HostsDesignation::where('hostId', $id);
            $hostDesignation->delete();
            
            $host=User::find($id);
            $host->delete();

            Session::flash('hostDeleteSuccess', 'Host removed!');
        }
        else{
            Session::flash('hostDeleteFailed', 'Host can not be removed!');
        }
        return redirect()->route('hosts.index');
    }
}

resources/views/hosts/create.blade.php
@extends('layouts.ap')

@section('title', 'Add Host')

@section('body')

<div id="content">
	<div id="content-header">
		<div id="breadcrumb"> <a href="{{ route('dashboard') }}" title="Dashboard" class="tip-bottom"><i class="fa fa-home" aria-hidden="true"></i> Home</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('hosts.index') }}" class="tip-bottom">Hosts</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('hosts.create') }}" class="current">Create</a></div>
		{{-- <h1>Add Host</h1> --}}
	</div>
	
	<div class="container-fluid">
		{{-- <hr> --}}
		<br><br>
		<div class="row-fluid">
			<div class="span6 offset3">
				<div class="widget-box">
					<div class="widget-title"> <span class="icon"> <i class="fa fa-align-justify" aria-hidden="true"></i> </span>
						<h5>Add Host</h5>
					</div>
					<div class="widget-content nopadding">
						<form action="{{ route('hosts.store') }}" method="POST" class="form-horizontal">
							@if(Session::has('hostAddSuccess'))
							<div class="alert alert-success">
								<button type="button" class="close" data-dismiss="alert">&times;</button>
								{{ Session::get('hostAddSuccess') }}
							</div>
							@endif

							{{ csrf_field() }}
							<div class="control-group">
								<label class="control-label">Host's Name :</label>
								<div class="controls">
									<input type="text" class="span11" name="name" placeholder="Host name" required>
									@if($errors->has('name'))
									<li class="error">{{ $errors->first('name') }}</li>
									@endif
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">Host's Email :</label>
								<div class="controls">
									<input type="email" class="span11" name="email" placeholder="Host email" required>
									@if($errors->has('email'))
									<li class="error">{{ $errors->first('email') }}</li>
									@endif
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">Host's Designation :</label>
								<div class="controls">
									<select class="span11" name="designationId" required>
										<option value="">Chose Designation...</option>
										@if(!$designations->isEmpty())
											@foreach($designations as $designation)
											<option value="{{ $designation->id }}">{{ ucwords($designation->name) }}</option>
											@endforeach
										@endif
									</select>
									@if($errors->has('designation'))
									<li class="error">{{ $errors->first('designation') }}</li>
									@endif
								</div>
							</div>
							<input type="hidden" name="role" value="host">
							<div class="control-group">
								<label class="control-label">Host's Password :</label>
								<div class="controls">
									<input type="password" class="span11" name="password" placeholder="Host password" required>
									<span class="help-block">At least 5 digits</span>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">Repeat Password :</label>
								<div class="controls">
									<input type="password" class="span11" name="password_confirmation" placeholder="Repeat password" required>
									@if($errors->has('password'))
									<li class="error">{{ $errors->first('password') }}</li>
									@endif
								</div>
							</div>
							<div class="form-actions">
								<button type="submit" class="btn btn-success">Save</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/hosts/index.blade.php
@extends('layouts.ap')

@section('title', 'Hosts')

@section('body')

<div id="content">
	<div id="content-header">
		<div id="breadcrumb"> <a href="{{ route('dashboard') }}" title="Dashboard" class="tip-bottom"><i class="fa fa-home" aria-hidden="true"></i> Home</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('hosts.index') }}" class="current">Hosts</a></div>
		{{-- <h1>Hosts</h1> --}}
	</div>
	
	<div class="container-fluid">
		{{-- <hr> --}}
		<br><br>
		<div class="row-fluid">
			<div class="span10 offset1">
				@if(Session::has('hostDeleteSuccess'))
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					{{ Session::get('hostDeleteSuccess') }}
				</div>
				@endif
				@if(Session::has('hostDeleteFailed'))
				<div class="alert alert-danger">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					{{ Session::get('hostDeleteFailed') }}
				</div>
				@endif
				@if(Session::has('mailSent'))
				<div class="row-fluid">
					<div class="span12">
						<div class="alert alert-success">{!! Session::get('mailSent') !!}</div>
					</div>
				</div>
				@endif

				@if(Session::has('mailNotSent'))
				<div class="row-fluid">
					<div class="span12">
						<div class="alert alert-danger">{!! Session::get('mailNotSent') !!}</div>
					</div>
				</div>
				@endif

				<div class="widget-box">
					<div class="widget-title"> <span class="icon"><i class="fa fa-th"></i></span>
						<h5>Hosts List</h5>
					</div>

					<div class="widget-content nopadding">
						@if($hosts->isEmpty())
							<div class="alert alert-warning">No host found! <a href="{{ route('hosts.create') }}">Add new</a></div>
						@else
						<table class="table table-bordered data-table">
							<thead>
								<tr>
									<th>Sl</th>
									<th>Name</th>
									<th>Email</th>
									<th>Designation</th>
									<th>Registered At</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@php($count=0)
								@foreach($hosts as $host)
								@php($count++)
								<tr>
									<td>{{ $count }}</td>
									<td>{{ $host->name }}</td>
									<td>{{ $host->email }}</td>
									<td>{{ ucwords($host->designation) }}</td>
									<td>{{ date('F j, Y, g:i a', strtotime($host->created_at)) }}</td>
									<td>
										<a class="btn btn-success btn-mini tip-left" title="View Profile" href="{{ route('profiles.show', $host->id) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>

										<button class="btn btn-info btn-mini tip-top mailUser" data-toggle="modal" data-target="#mailUser{{ $host->id }}"><i class="fa fa-envelope" aria-hidden="true"></i></button>

										@if($errors->has('subject') || $errors->has('body'))
										<script>
											$(document).ready(function(){
												$($('.mailUser').data('target')).modal('show');
											});
										</script>
										@endif

										<div id="mailUser{{ $host->id }}" class="modal hide" style="text-align: left !important">
											<form action="{{ route('mail.send', $host->id) }}" method="POST">
											{{ csrf_field() }}
											<div class="modal-header">
												<button data-dismiss="modal" class="close" type="button">×</button>
												<h3>Mail To: {{ $host->name }}</h3>
											</div>
											<div class="modal-body">
												<div class="control-group">
													<label class="control-label">Subject :</label>
													<div class="controls">
														<input type="text" class="span12" name="subject" placeholder="Mail Subject" required>
														@if($errors->has('subject'))
														<li class="error">{{ $errors->first('subject') }}</li>
														@endif
														<span class="help-block">At least 5 words</span>
													</div>
												</div>

												<div class="control-group">
													<label class="control-label">Body :</label>
													<div class="controls">
														<textarea name="body" class="span12" cols="30" rows="6" placeholder="Write here" required></textarea>
														@if($errors->has('body'))
														<li class="error">{{ $errors->first('body') }}</li>
														@endif
														<span class="help-block">At least 15 words</span>
													</div>
												</div>
											</div>
											<div class="modal-footer">
												<button type="submit" class="btn btn-primary">Send</button>
												<button data-dismiss="modal" class="btn">Cancel</button>
											</div>
											</form>
										</div>

										<form action="{{ route('hosts.destroy', $host->id) }}" method="POST" class="form-inline tip-bottom" title="Remove {{ $host->name }}">
											{{ csrf_field() }}
											{{ method_field('DELETE') }}
											<button type="submit" class="btn btn-danger btn-mini" onclick="return confirm('Are you sure?')"><i class="fa fa-trash" aria-hidden="true"></i></button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						@endif
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

@endsection