routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Pages
Route::get('/', 'PagesController@home')->name('home');

// Auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('postLogin');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register')->name('postRegister');

// Dashboard
Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');

// VisitReasons
Route::resource('visitreasons', 'VisitReasonsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Designations
Route::resource('designations', 'DesignationsController', ['only' => ['index', 'create', 'store', 'update', 'destroy']]);

// Hosts
Route::resource('hosts', 'HostsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Visitors
Route::resource('visitors', 'VisitorsController', ['only' => ['index', 'destroy']]);

// Visits
Route::get('visits/approved', 'VisitsController@approved')->name('visits.approved');
Route::get('visits/pending', 'VisitsController@pending')->name('visits.pending');
Route::get('visits/rejected', 'VisitsController@rejected')->name('visits.rejected');
Route::resource('visits', 'VisitsController');

// Profiles
Route::resource('profiles', 'ProfilesController');

// Appointments
Route::get('appointments/specific/{id}', 'AppointmentsController@specific')->name('appointments.specific');
Route::get('appointments/approved', 'AppointmentsController@approved')->name('appointments.approved');
Route::get('appointments/pending', 'AppointmentsController@pending')->name('appointments.pending');
Route::get('appointments/rejected', 'AppointmentsController@rejected')->name('appointments.rejected');
Route::resource('appointments', 'AppointmentsController');

// Manage Visits
Route::get('managevisits/approved', 'ManageVisitsController@approved')->name('managevisits.approved');
Route::get('managevisits/pending', 'ManageVisitsController@pending')->name('managevisits.pending');
Route::get('managevisits/rejected', 'ManageVisitsController@rejected')->name('managevisits.rejected');
Route::resource('managevisits', 'ManageVisitsController');

// Visit Access Codes
Route::get('visits/approved/download/{id}', 'VisitAccessCodesController@download')->name('visitDownload');

// Manage Appointments
Route::get('manageappointments/approved', 'ManageAppointmentsController@approved')->name('manageappointments.approved');
Route::get('manageappointments/pending', 'ManageAppointmentsController@pending')->name('manageappointments.pending');
Route::get('manageappointments/rejected', 'ManageAppointmentsController@rejected')->name('manageappointments.rejected');
Route::resource('manageappointments', 'ManageAppointmentsController');

// Appointment Access Codes
Route::get('appointments/approved/download/{id}', 'AppointmentAccessCodesController@download')->name('appointmentDownload');

// Mail
Route::post('mail/{id}', 'MailController@send')->name('mail.send');

// Visit Reports
Route::get('checkvisits', 'VisitReportsController@index')->name('checkVisits.index');
Route::post('checkvisits', 'VisitReportsController@check')->name('checkVisits.check');
Route::post('checkvisits/proceed', 'VisitReportsController@proceed')->name('checkVisits.proceed');
Route::post('checkvisits/terminate', 'VisitReportsController@terminate')->name('checkVisits.terminate');

// Appointment Reports
Route::get('checkappointments', 'AppointmentReportsController@index')->name('checkAppointments.index');
Route::post('checkappointments', 'AppointmentReportsController@check')->name('checkAppointments.check');
Route::post('checkappointments/proceed', 'AppointmentReportsController@proceed')->name('checkAppointments.proceed');
Route::post('checkappointments/terminate', 'AppointmentReportsController@terminate')->name('checkAppointments.terminate');

// AR Visit Reports
Route::get('visitreports', 'ARVisitReportsController@index')->name('visitReports.index');
Route::get('visitreports/{id}', 'ARVisitReportsController@show')->name('visitReports.show');
Route::get('visitstoday', 'ARVisitReportsController@today')->name('visitReports.today');

// AR Appointment Reports
Route::get('appointmentreports', 'ARAppointmentReportsController@index')->name('appointmentReports.index');
Route::get('appointmentreports/{id}', 'ARAppointmentReportsController@show')->name('appointmentReports.show');
Route::get('appointmentstoday', 'ARAppointmentReportsController@today')->name('appointmentReports.today');

// Inbox
Route::get('inbox', 'InboxesController@index')->name('inbox.index');
Route::post('inbox/{id}', 'InboxesController@store')->name('inbox.store');

// Immediate Visits
Route::resource('immediatevisits', 'ImmediateVisitsController', ['only' => ['index', 'create', 'store', 'destroy']]);

// Immediate Appointments
Route::resource('immediateappointments', 'ImmediateAppointmentsController', ['only' => ['index', 'create', 'store', 'show', 'destroy']]);

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    public function user()
    {
    	return $this->belongsTo('App\User', 'userId', 'id');
    }
}

app/Http/Controllers/ProfilesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profile;
use App\User;
use Image;
use Auth;
use File;

class ProfilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // return view('profiles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user=User::find($id);
        $profile=Profile::where('userId', $id)->first();

        if(!empty($user) && !empty($profile))
            return view('profiles.show')->withUser($user)->withProfile($profile);
        else if(!empty($user) && empty($profile))
            return view('profiles.show')->withUser($user);
        else
            return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->id!=$id)
            return abort(403);
        else{
            $profile=Profile::where('userId', $id)->first();

            if(!empty($profile))
                return view('profiles.edit')->withProfile($profile);
            else
                return view('profiles.edit');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, array(
            'name' => 'required|string|min:5|max:255',
            'phone' => 'required|numeric|min:5',
            'address' => 'required|min:5',
            'occupation' => 'required|min:3',
            'avatar' => 'image|mimes:jpeg,jpg,png|max:2560',
            'about' => 'required|min:5'
        ));

        $user=User::find($id);
        $user->name=ucwords($request->name);
        $user->save();

        $profile=Profile::where('userId', $id)->first();
        if(empty($profile)){
            $prf=new Profile();
            $prf->userId=Auth::user()->id;
            $prf->phone=$request->phone;
            $prf->address=$request->address;
            $prf->occupation=$request->occupation;

            if($request->hasFile('avatar')){
                $avatar=$request->file('avatar');
                $filename=Auth::user()->id.'_'.time().'.'.$avatar->getClientOriginalExtension();
                $location=public_path('images/avatar/'.$filename);
                Image::make($avatar)->resize(400, 400)->save($location);

                $prf->avatar=$filename;
            }

            $prf->about=$request->about;
            $prf->save();
        }
        else{
            $profile->phone=$request->phone;
            $profile->address=$request->address;
            $profile->occupation=$request->occupation;

            if($request->hasFile('avatar')){
                $delPrev=public_path().'/images/avatar/'.$profile->avatar;
                if(file_exists($delPrev))
                    File::Delete($delPrev);

                $avatar=$request->file('avatar');
                $filename=Auth::user()->id.'_'.time().'.'.$avatar->getClientOriginalExtension();
                $location=public_path('images/avatar/'.$filename);
                Image::make($avatar)->resize(400, 400)->save($location);

                $profile->avatar=$filename;
            }

            $profile->about=$request->about;
            $profile->save();
        }

        return redirect()->route('profiles.show', Auth::user()->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/profiles/edit.blade.php
@extends('layouts.ap')

@section('title', 'Edit Profile | '.Auth::user()->name)

@section('body')

<div id="content">
	<div id="content-header">
		<div id="breadcrumb"> <a href="{{ route('dashboard') }}" title="Dashboard" class="tip-bottom"><i class="fa fa-home" aria-hidden="true"></i> Home</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('profiles.index') }}" class="tip-bottom">Profiles</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('profiles.show', Auth::user()->id) }}" class="current">{{ Auth::user()->name }}</a></div>
		{{-- <h1>Add Designation</h1> --}}
	</div>
	
	<div class="container-fluid">
		{{-- <hr> --}}
		<br><br>
		<div class="row-fluid">
			<div class="span12">
				<div class="widget-box">
					<div class="widget-title"> <span class="icon"> <i class="fa fa-align-justify" aria-hidden="true"></i> </span>
						<h5>Update User Profile</h5>
					</div>
					<div class="widget-content">
						<form action="{{ route('profiles.update', Auth::user()->id) }}" method="POST" enctype="multipart/form-data" class="form-horizontal">
							<div class="row-fluid">
								<div class="span6">
									{{-- @if(Session::has('designationAddSuccess'))
									<div class="alert alert-success">
										<button type="button" class="close" data-dismiss="alert">&times;</button>
										{{ Session::get('designationAddSuccess') }}
									</div>
									@endif --}}
									{{ csrf_field() }}
									{{ method_field('PUT') }}

									<div class="control-group">
										<label class="control-label">Name :</label>
										<div class="controls">
											<input type="text" class="span11" name="name" placeholder="Name" value="{{ Auth::user()->name }}" required>
											@if($errors->has('name'))
											<li class="error">{{ $errors->first('name') }}</li>
											@endif
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Email :</label>
										<div class="controls">
											<input type="email" class="span11" name="email" placeholder="Email" value="{{ Auth::user()->email }}" readonly>
											{{-- @if($errors->has('name'))
											<li class="error">{{ $errors->first('name') }}</li>
											@endif --}}
											<span class="help-block">You can't change email</span>
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">User Role :</label>
										<div class="controls">
											<input type="text" class="span11" name="role" placeholder="Role" value="{{ Auth::user()->role }}" readonly>
											{{-- @if($errors->has('name'))
											<li class="error">{{ $errors->first('name') }}</li>
											@endif --}}
											<span class="help-block">You can't change role</span>
										</div>
									</div>
								</div>

								<div class="span6">
									<div class="control-group">
										<label class="control-label">Phone No :</label>
										<div class="controls">
											<input type="text" class="span11" name="phone" placeholder="Phone No" value="{{ isset($profile) ? $profile->phone : '' }}" required>
											@if($errors->has('phone'))
											<li class="error">{{ $errors->first('phone') }}</li>
											@endif
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Address :</label>
										<div class="controls">
											<input type="text" class="span11" name="address" placeholder="Address" value="{{ isset($profile) ? $profile->address : '' }}" required>
											@if($errors->has('address'))
											<li class="error">{{ $errors->first('address') }}</li>
											@endif
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Occupation :</label>
										<div class="controls">
											<input type="text" class="span11" name="occupation" placeholder="Occupation" value="{{ isset($profile) ? $profile->occupation : '' }}" required>
											@if($errors->has('occupation'))
											<li class="error">{{ $errors->first('occupation') }}</li>
											@endif
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Profile Avatar :</label>
										<div class="controls">
											@if(isset($profile) && $profile->avatar!=NULL)
											<input type="file" name="avatar">
											@else
											<input type="file" name="avatar" required>
											@endif
											@if($errors->has('avatar'))
											<li class="error">{{ $errors->first('avatar') }}</li>
											@endif
										</div>
									</div>
								</div>
							</div>
							
							<div class="row-fluid">
								<div class="span12">
									<div class="control-group">
										<label class="control-label">About You :</label>
										<div class="controls">
											<textarea name="about" class="span11" cols="30" rows="10" placeholder="About You" required>{{ isset($profile) ? $profile->about : '' }}</textarea>
											@if($errors->has('about'))
											<li class="error">{{ $errors->first('about') }}</li>
											@endif
										</div>
									</div>
								</div>
							</div>

							<div class="row-fluid">
								<div class="span12">
									<button type="submit" class="btn btn-success">Update</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

@endsection

resources/views/profiles/show.blade.php
@extends('layouts.ap')

@section('title', $user->name)

@section('body')

<div id="content">
	<div id="content-header">
		<div id="breadcrumb"> <a href="{{ route('dashboard') }}" title="Dashboard" class="tip-bottom"><i class="fa fa-home" aria-hidden="true"></i> Home</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('profiles.index') }}" class="tip-bottom">Profiles</a> <i class="fa fa-angle-right" aria-hidden="true"></i> <a href="{{ route('profiles.show', $user->id) }}" class="current">{{ $user->name }}</a></div>
		{{-- <h1>Add Designation</h1> --}}
	</div>
	
	<div class="container-fluid">
		{{-- <hr> --}}
		<br><br>
		<div class="row-fluid">
			<div class="span12">
				<div class="widget-box">
					<div class="widget-title"> <span class="icon"> <i class="fa fa-user-circle-o" aria-hidden="true"></i> </span>
						<h5>User Profile</h5>
					</div>
					<div class="widget-content">
						<div class="row-fluid">
							<div class="span4">
								{{-- @if(isset($user->hostDesignation))
								{{ $user->hostDesignation->designation->name }}
								@endif --}}
								<br><br>
								@if(!isset($profile))
									<div class="avatar">
										<img src="{{ asset('images/avatar/noimage.png') }}" class="img-polaroid" width="170px" height="170px" alt="">
									</div>
								@else
									<div class="avatar">
										<img src="{{ asset('images/avatar/'.$profile->avatar) }}" class="img-polaroid" width="170px" height="170px" alt="">
									</div>
								@endif
								<h4>{{ $user->name }}</h4>

								@if($user->role=='host')
								<span><i class="fa fa-star"></i> {{ ucwords($user->hostDesignation->designation->name) }}</span>
								<br><br>
								@endif
								<span class="label">{{ ucwords($user->role) }}</span>

								@if(Auth::user()->id==$user->id)
								<p>{{ $user->email }}</p>
								@else
								<br>
								<a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
								@endif
							</div>

							<div class="span8">
								<div class="profile-action text-right">
								@if(Auth::user()->id==$user->id)
									<a class="btn btn-success btn-mini" href="{{ route('profiles.edit', Auth::user()->id) }}">Edit Profile</a>
								@endif
								@if(Auth::user()->role=='admin' && Auth::user()->id!=$user->id)
									<a class="btn btn-danger btn-mini" href="#">Remove User</a>
								@endif
								</div>
								<br>

								<table class="table table-bordered table-invoice">
									<tbody>
										<tr>
											<tr>
												<td class="width30">Name:</td>
												<td class="width70"><strong>{{ $user->name }}</strong></td>
											</tr>
											<tr>
												<td>Email:</td>
												<td>
													<strong>{{ $user->email }}</strong>
													@if(Auth::user()->id!=$user->id)
													<button class="btn btn-info btn-mini mailUser" style="float: right" data-toggle="modal" data-target="#mailUser{{ $user->id }}"><i class="fa fa-envelope"></i></button>
													@endif
												</td>
											</tr>
											<tr>
												<td>Phone:</td>
												<td>
													<strong>{{ isset($profile) ? $profile->phone : '--' }}</strong>
												</td>
											</tr>
											<tr>
												<td>Registered In:</td>
												<td>{{ date('F j, Y, g:i a', strtotime($user->created_at)) }}</td>
											</tr>
											<tr>
												<td>Occupation:</td>
												<td>
													{{ isset($profile) ? $profile->occupation : '--' }}
												</td>
											</tr>
											<tr>
												<td>Address:</td>
												<td>
													{{ isset($profile) ? $profile->address : '--' }}
												</td>
											</tr>
											<tr>
												<td>About {{ $user->name }}:</td>
												<td>{{ isset($profile) ? $profile->about : '--' }}</td>
											</tr>
										</tr>
									</tbody>

								</table>
							</div>
						</div>
						@if(Session::has('mailSent'))
						<div class="row-fluid">
							<div class="span12">
								<div class="alert alert-success">{!! Session::get('mailSent') !!}</div>
							</div>
						</div>
						@endif
						@if(Session::has('mailNotSent'))
						<div class="row-fluid">
							<div class="span12">
								<div class="alert alert-danger">{!! Session::get('mailNotSent') !!}</div>
							</div>
						</div>
						@endif
						@if(Session::has('messageSent'))
						<div class="row-fluid">
							<div class="span12">
								<div class="alert alert-success">{!! Session::get('messageSent') !!}</div>
							</div>
						</div>
						@endif
						<hr>
						<div class="row-fluid">
							<div class="span12 text-right">
								@if(Auth::user()->id!=$user->id)
									@if(Auth::user()->role=='visitor' && $user->role=='host')
									<a class="btn btn-info btn-mini" href="{{ route('appointments.specific', $user->id) }}">Request for Appointment</a>
									@elseif(Auth::user()->role=='visitor' && $user->role=='admin')
									<a class="btn btn-info btn-mini" href="{{ route('visits.create') }}">Request for Visit</a>
									@endif
								<button class="btn btn-info btn-mini" data-toggle="modal" data-target="#msgUser{{ $user->id }}">Send Message</button>
								
								<div id="msgUser{{ $user->id }}" class="modal hide" style="text-align: left !important">
									<form action="{{ route('inbox.store', $user->id) }}" method="POST">
									{{ csrf_field() }}
									<div class="modal-header">
										<button data-dismiss="modal" class="close" type="button">×</button>
										<h3>Message To: {{ $user->name }}</h3>
									</div>
									<div class="modal-body">
										<div class="control-group">
											<label class="control-label">Message :</label>
											<div class="controls">
												<textarea name="message" class="span12" cols="30" rows="6" placeholder="Write here" required></textarea>
												@if($errors->has('message'))
												<li class="error">{{ $errors->first('message') }}</li>
												@endif
											</div>
										</div>
									</div>
									<div class="modal-footer">
										<button type="submit" class="btn btn-primary">Send</button>
										<button data-dismiss="modal" class="btn">Cancel</button>
									</div>
									</form>
								</div>

								<button class="btn btn-info btn-mini mailUser" data-toggle="modal" data-target="#mailUser{{ $user->id }}">Send Mail</button>
								
								@if($errors->has('subject') || $errors->has('body'))
								<script>
									$(document).ready(function(){
										$($('.mailUser').data('target')).modal('show');
									});
								</script>
								@endif

								<div id="mailUser{{ $user->id }}" class="modal hide" style="text-align: left !important">
									<form action="{{ route('mail.send', $user->id) }}" method="POST">
									{{ csrf_field() }}
									<div class="modal-header">
										<button data-dismiss="modal" class="close" type="button">×</button>
										<h3>Mail To: {{ $user->name }}</h3>
									</div>
									<div class="modal-body">
										<div class="control-group">
											<label class="control-label">Subject :</label>
											<div class="controls">
												<input type="text" class="span12" name="subject" placeholder="Mail Subject" required>
												@if($errors->has('subject'))
												<li class="error">{{ $errors->first('subject') }}</li>
												@endif
												<span class="help-block">At least 5 words</span>
											</div>
										</div>

										<div class="control-group">
											<label class="control-label">Body :</label>
											<div class="controls">
												<textarea name="body" class="span12" cols="30" rows="6" placeholder="Write here" required></textarea>
												@if($errors->has('body'))
												<li class="error">{{ $errors->first('body') }}</li>
												@endif
												<span class="help-block">At least 15 words</span>
											</div>
										</div>
									</div>
									<div class="modal-footer">
										<button type="submit" class="btn btn-primary">Send</button>
										<button data-dismiss="modal" class="btn">Cancel</button>
									</div>
									</form>
								</div>

								@else
									@if(Auth::user()->role=='admin')
										<a class="btn btn-info btn-mini" href="{{ route('managevisits.index') }}">Manage Visit Requests</a>
									@elseif(Auth::user()->role=='host')
										<a class="btn btn-info btn-mini" href="{{ route('manageappointments.index') }}">Manage Appointment Requests</a>
									@elseif(Auth::user()->role=='visitor')
										<a class="btn btn-info btn-mini" href="{{ route('visits.index') }}">My Visit Requests</a>
										<a class="btn btn-info btn-mini" href="{{ route('appointments.index') }}">My Appointment Requests</a>
									@endif
								@endif
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection